### ISSUE TITLE
Prosody Docker image does not start. The resulting container is constantly restarting

### ISSUE THREAD

**Issue by unclev** [unclev/prosody-docker-extended#6]
**Jean-Philippe Baril** wrote:
> I tried to use your Prosody Docker image but it does not start. The resulting container is constantly restarting.

> What docker shows as logs :

```
xmpp_server_1  | ++ id -u
xmpp_server_1  | ++ id -u prosody
xmpp_server_1  | + [[ 1000 -eq 1000 ]]
xmpp_server_1  | ++ ls -A /etc/prosody
xmpp_server_1  | ++ head -1
xmpp_server_1  | + [[ -z '' ]]
xmpp_server_1  | + cp -Rv /etc/prosody.default/certs /etc/prosody.default/migrator.cfg.lua /etc/prosody.default/prosody.cfg.lua /etc/prosody/
xmpp_server_1  | cp: cannot create directory '/etc/prosody/certs': Permission denied
xmpp_server_1  | '/etc/prosody.default/migrator.cfg.lua' -> '/etc/prosody/migrator.cfg.lua'
xmpp_server_1  | '/etc/prosody.default/prosody.cfg.lua' -> '/etc/prosody/prosody.cfg.lua'
xmpp_server_1  | cp: cannot create regular file '/etc/prosody/migrator.cfg.lua': Permission denied
xmpp_server_1  | cp: cannot create regular file '/etc/prosody/prosody.cfg.lua': Permission denied
```

> Here is what I used as docker-compose.yml :

```yml
xmpp_server:
  image: unclev/prosody-docker-extended:0.10
  restart: unless-stopped
  hostname: *censored*
  ports:
    - 5222:5222
    - 5269:5269
    - 5347:5347
    - 5280:5280
  volumes:
    - './config:/etc/prosody'
    - './data:/var/lib/prosody'
    - './log:/var/log/prosody'
    - './modules/community:/usr/lib/prosody/modules-community'
    - './modules/custom:/usr/lib/prosody/modules-custom'
```

> Thanks for your help and for the Docker image.
